{% set version = "2.0.0" %}

package:
  name: hiredis
  version: {{ version }}

source:
  url: https://pypi.python.org/packages/source/h/hiredis/hiredis-{{ version }}.tar.gz
  sha256: 81d6d8e39695f2c37954d1011c0480ef7cf444d4e3ae24bc5e89ee5de360139a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - hiredis

about:
  home: https://github.com/redis/hiredis-py
  license: BSD-3-Clause
  license_file: COPYING
  summary: Python wrapper for hiredis

extra:
  recipe-maintainers:
    - kwilcox
    - mariusvniekerk
