{% set version = "0.2.0" %}

package:
    name: hiredis
    version: {{ version }}

source:
    fn: hiredis-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/source/h/hiredis/hiredis-{{ version }}.tar.gz
    md5: b410cf2f2062d87ab841c33d8345761e

build:
    noarch: python
    number: 1
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - hiredis

about:
    home: https://github.com/redis/hiredis-py
    license: BSD
    summary: Python wrapper for hiredis

extra:
    recipe-maintainers:
        - kwilcox
