{% set version = "0.3.0" %}

package:
    name: hiredis
    version: {{ version }}

source:
    fn: hiredis-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/source/h/hiredis/hiredis-{{ version }}.tar.gz
    md5: 3a45c0298ab89768ae09b8943d04c5a3

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - hiredis

about:
    home: https://github.com/redis/hiredis-py
    license: BSD
    summary: Python wrapper for hiredis

extra:
    recipe-maintainers:
        - kwilcox
