{% set version = "3.1.0" %}

package:
  name: hiredis
  version: {{ version }}

source:
  url: https://pypi.python.org/packages/source/h/hiredis/hiredis-{{ version }}.tar.gz
  sha256: 51d40ac3611091020d7dea6b05ed62cb152bff595fa4f931e7b6479d777acf7c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - hiredis

about:
  home: https://github.com/redis/hiredis-py
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python wrapper for hiredis

extra:
  recipe-maintainers:
    - kwilcox
    - mariusvniekerk
