schema_version: 1

context:
  version: "3.4.0"

package:
  name: hiredis
  version: ${{ version }}

source:
  url: https://pypi.python.org/packages/source/h/hiredis/hiredis-${{ version }}.tar.gz
  sha256: da19331354433af6a2c54c21f2d70ba084933c0d7d2c43578ec5c5b446674ad5

build:
  number: 1
  script: python -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

tests:
  - python:
      imports:
        - hiredis
      pip_check: true

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python wrapper for hiredis
  homepage: https://github.com/redis/hiredis-py

extra:
  recipe-maintainers:
    - kwilcox
    - mariusvniekerk
    - synapticarbors
