appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: MgkUEqxNrANvaNO16H+pMWCb29Ma7MELy3Itt6LyDMARO2TIy/O5Y6S4Ch9TiEd8p0mF1LQVL0oEotCv6mqLYYSL1o+9eRDBrFWYxX1E9cZQZQaB40QlHhRWt7FBmwobHktovaRfJJc+dPDW6kt26B8msixNGl2OYRIhWi6hmXnCW3rNBBBllv+cNjPHJVmRHCervqXm+1Ind9JJEMV6o6tyHJ+0N6sfwqM7OBcXBdtTbcMKqsg9BmrRPNfp0iTh7UgwHAyv4lIuFmw/P8Lkt7IUwjp4rPmjoU6iXI1dBE2rdUKIMD06tCCDWkeyEPsTmZAopSo/lbv1kfNJ3TuKlM2wZkopD5WqFw5lziFzEx65/Jx77FBJ6LwDIWMXWM7vDp4t+ZYxmlH2VNVdS6klQ97i/wZuwrTC9aVCR1IDKgGRHWW+Xcj/J9EMbB6mPWUcL4/CNVYB1Zz9RfOqDn0gWQX1c34VAKYSBBOPRRKTLpnHjIFAsfreQOatPbl1JX4DpFYpK+PGEFytB3zIQb06B5Pfb+XHPFz868kCw03wkWpi2/ODtnlCy1thTVyroUWrPA718/n4YJpwCHRy3BzcHAiQIFk3TXAhvWmfXOdcwKHxxJC3EH7KUOGQklVQq361VK9RTNYqpE3HBaaV+BgOInC3bNv7SgmQU71VkvXE2Dg=}
